### ISSUE TITLE
(GUI) Physics Material Editor handles selected file path incorrectly

### ISSUE THREAD

**Issue by its5Q** [SpaRcle-Studio/SREngine#102]
**Describe the bug**
Physics Material Editor, when selecting a file from the assets window, tries to concatenate an already absolute path with a path to engine resources, leading to an incorrect path.

**To Reproduce**
1. Open Physics Material Editor
2. Try to load any random file
3. Observe an error with two absolute paths concatenated

**Expected behavior**
Path handling should be correct

**Desktop (please complete the following information):**
 - OS: any
 - Compiler: MSVC

**Comment by innerviewer** [comment]
Closed thanks to @its5Q by 53d5597.
