### ISSUE TITLE
(Vulkan) Make vulkan cross-project

### ISSUE THREAD

**Issue by Monika0000** [SpaRcle-Studio/SREngine#150]
Use library https://github.com/KhronosGroup/Vulkan-Headers/tree/cfebfc96b2b0bce93da7d12f2c14cc01793ae25c

**Comment by innerviewer** [comment]
Vulkan is now built statically. Commit [00b1eef](https://github.com/SpaRcle-Studio/EvoVulkan/commit/00b1eef5b0965d9ac4b24d4aa0ef548c06ae5455).
