### ISSUE TITLE
Invalid source ID.

### ISSUE THREAD

**Issue by innerviewer** [SpaRcle-Studio/SREngine#20]
**Describe the bug**
Sometimes the bug may occur when the audio initializes.

**Screenshots**
Attached a screenshot of the error logs.

![image](https://github.com/Monika0000/SREngine/assets/121586699/b7e56ca7-601d-4feb-aab7-300ec2ec5732)

**Comment by CaptainSlider** [comment]
(Audio) Fixed potential multi-threading error while creating a sound
